name: CodeQL
 
on:
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: List available Xcode versions
        run: ls /Applications/
      
      - name: Select Xcode version
        run: |
          AVAILABLE_XCODE=$(ls /Applications/ | grep -E 'Xcode_[0-9]+\.[0-9]+\.app' | sort -r | head -n 1)
          if [ -z "$AVAILABLE_XCODE" ]; then
            echo "No Xcode version found."
            exit 1
          fi
          echo "Found Xcode version: $AVAILABLE_XCODE"
          sudo xcode-select -s /Applications/$AVAILABLE_XCODE/Contents/Developer

      # Other steps in your job
