name: "CodeQL"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  analyze:
    name: Analyze
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'swift' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize the CodeQL tools
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    
    - name: Build Swift project
      run: |
        xcodebuild clean build -project SUSTAINForiOS.xcodeproj -scheme SUSTAINForiOS -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4'
        
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
